"""Ajout parrain_email, lieu_naissance, is_admin, is_online

Revision ID: 221cd31e473d
Revises: 89120ad31bfb
Create Date: 2025-10-14 14:18:30.297249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '221cd31e473d'
down_revision = '89120ad31bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('users', sa.Column('parrain_email', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parrain_email')
    op.create_table('video_questions',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('question', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('choix', mysql.JSON(), nullable=True),
    sa.Column('bonne_reponse', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('niveau', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('serie', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('matiere', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remediation_video_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['remediation_video_id'], ['remediation_videos.id'], name='video_questions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('remediation_videos',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('titre', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('niveau', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('serie', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('matiere', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mois', mysql.JSON(), nullable=True),
    sa.Column('videoUrl', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('notions', mysql.JSON(), nullable=True),
    sa.Column('prerequis', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('questions',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('niveau', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('serie', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('matiere', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('choix', mysql.JSON(), nullable=True),
    sa.Column('bonne_reponse', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('situation', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('remediation_progress',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('matiere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('notion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('niveau', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('statut', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_actuelle_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('test_termine', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('test_score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='remediation_progress_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
