"""initial migration

Revision ID: fbce9ca543de
Revises: 
Create Date: 2025-09-19 21:24:02.661141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbce9ca543de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nom', sa.String(length=100), nullable=False),
        sa.Column('prenom', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('telephone', sa.String(length=20), nullable=True),
        sa.Column('sexe', sa.String(length=1), nullable=True),
        sa.Column('date_naissance', sa.Date(), nullable=True),
        sa.Column('lieu_naissance', sa.String(length=255), nullable=True),
        sa.Column('nationalite', sa.String(length=100), nullable=True),
        sa.Column('pays_residence', sa.String(length=100), nullable=True),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('plain_password', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('validation_token', sa.String(length=255), nullable=True),
        sa.Column('is_validated', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('is_blocked', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('last_warning', sa.DateTime(), nullable=True),
        sa.Column('date_inscription', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('reset_token', sa.String(length=255), nullable=True),
        sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nom'), 'users', ['nom'], unique=False)
    op.create_index(op.f('ix_users_prenom'), 'users', ['prenom'], unique=False)
    op.create_index(op.f('ix_users_telephone'), 'users', ['telephone'], unique=False)
    # ### end Alembic commands ###

  


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('niveau', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('serie', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('matiere', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('choix', mysql.JSON(), nullable=True),
    sa.Column('bonne_reponse', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('situation', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('video_questions',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('question', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('choix', mysql.JSON(), nullable=True),
    sa.Column('bonne_reponse', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('niveau', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('serie', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('matiere', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remediation_video_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['remediation_video_id'], ['remediation_videos.id'], name='video_questions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('remediation_videos',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('titre', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('niveau', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('serie', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('matiere', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mois', mysql.JSON(), nullable=True),
    sa.Column('videoUrl', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('notions', mysql.JSON(), nullable=True),
    sa.Column('prerequis', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_users_telephone'), table_name='users')
    op.drop_index(op.f('ix_users_prenom'), table_name='users')
    op.drop_index(op.f('ix_users_nom'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
